### ISSUE TITLE
photons_control.device_finder error

### ISSUE THREAD

**Issue by gabemunro** [delfick/photons#17]
Back with one other challenge. Thank you again for creating this. It really resolves my biggest annoyance with my Beam (the inability to trigger animations via HomeKit).

I installed the most recent release on a fresh machine yesterday, and started running into a challenge. Photons works great for a while (I have Interactor running as an agent via launchctl), but then I get the below error and the service stops responding. Bouncing it via launchctl returns everything to normal, but it's happening every few hours. Any ideas?

Some additional context - macOS 10.15.6, and working behind ExpreessVPN

2020-07-29 09:25:02,752 ERROR   photons_control.device_finder Something went wrong in a search
Traceback (most recent call last):
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_control/device_finder.py", line 736, in search_loop
    async for device in self.finder.find(refresh_discovery_fltr):
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_control/device_finder.py", line 819, in find
    _, removed = await self._ensure_devices(fltr)
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_control/device_finder.py", line 795, in _ensure_devices
    serials = await self.searcher.discover(
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_control/device_finder.py", line 771, in discover
    serials = await self._serials()
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_control/device_finder.py", line 761, in _serials
    _, serials = await FoundSerials().find(self.sender, timeout=5)
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_app/special.py", line 70, in find
    return await self.found
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_app/helpers.py", line 1137, in __await__
    return (yield from self.info["fut"])
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_app/special.py", line 85, in find_serials
    return await sender.find_devices(timeout=timeout, broadcast=broadcast, raise_on_none=True)
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_transport/comms/base.py", line 281, in find_devices
    found, _ = await self.find_specific_serials(None, **kwargs)
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_transport/comms/base.py", line 289, in find_specific_serials
    found = await self._find_specific_serials(serials, **kwargs)
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_transport/comms/base.py", line 307, in _find_specific_serials
    raise FoundNoDevices()
photons_app.errors.FoundNoDevices: "Didn't find any devices"
2020-07-29 09:25:14,977 INFO    photons_transport.transports.udp Creating datagram endpoint	address=('XXX.XXX.XXX.XXX', 56700)	serial=XXXXXXXXXX

**Comment by delfick** [comment]
oops, nice find :) 

I'm nearly finished what I [started](https://github.com/delfick/photons/compare/35e8005e85422ffb8c0f1d22863ca3951b3b180c...main) last week so this should be released this weekend or next weekend.

In the meantime, master also has a fix to a memory leak.

So in your virtualenv, do something like

```
pip uninstall lifx-photons-core
pip install -e /path/to/photons/modules
```

And I'll let you know here when the new version has been made :)
