### ISSUE TITLE
RFE: Need to way to tell Interactor to stop gracefully

### ISSUE THREAD

**Issue by Djelibeybi** [delfick/photons#41]
Currently, the only way to stop `lifx lan:interactor` is by killing the process, which makes `systemd` rather cross about the whole situation and renders `Restart=on-failure` a bit hit and miss. 

It would be good if the `status` command took an optional boolean parameter `shutdown` and if that parameter is `true`, Interactor would shut itself down.

I'd add this myself, but I don't know how to tell Interactor to end. 😂

**Comment by Final-Hawk** [comment]
The only way i know how to stop it gracefully is ctl+c When you start it manually. Not sure if there's any other way implemented at the moment￼

**Comment by delfick** [comment]
yeah, that should be easy. I'll do that a bit later.

Sigterm is graceful but it causes the app to exit with status 1

**Comment by delfick** [comment]
I was wrong when I said "easy". sigh

**Comment by delfick** [comment]
Ok, fixed in #41

Specifically, https://github.com/delfick/photons/commit/2da982f548113c3950895cbb3532c9cb86948221

SIGTERM will no longer make the interactor (or the arranger) exit with status 1.

I've released Version 0.8.3 of interactor, and building the docker container now in https://github.com/delfick/photons/runs/2210707217

**Comment by Djelibeybi** [comment]
Sending a `SIGTERM` to the Interactor process still results in an exit code of 1. This is the error output after I sent a `kill -TERM <pid>`:

```bash
13:34:42 ERROR   photons_app.options_spec.photons_app_spec "The application itself was stopped"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/photons_app/option_spec/photons_app_spec.py", line 167, in cleanup
    await cleaner()
  File "/usr/local/lib/python3.9/site-packages/photons_control/device_finder.py", line 900, in finish
    async with hp.TaskHolder(
  File "/usr/local/lib/python3.9/site-packages/photons_app/helpers.py", line 89, in __aenter__
    return await self.start()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 182, in __aexit__
    await self.gen.__anext__()
  File "/usr/local/lib/python3.9/site-packages/photons_app/runner.py", line 70, in run
    loop.run_until_complete(waiter)
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/photons_app/runner.py", line 62, in wait
    await graceful_future
  File "/usr/local/lib/python3.9/site-packages/interactor/addon.py", line 36, in interactor
    await Server(final_future).serve(
  File "/usr/local/lib/python3.9/site-packages/whirlwind/server.py", line 28, in serve
    await self.final_future
photons_app.errors.ApplicationStopped: "The application itself was stopped"
13:34:42 ERROR   photons_app.options_spec.photons_app_spec "The application itself was stopped"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/photons_app/option_spec/photons_app_spec.py", line 167, in cleanup
    await cleaner()
  File "/usr/local/lib/python3.9/site-packages/interactor/commander/animations.py", line 142, in stop
    return await self.action("stop", "stopping", identities)
  File "/usr/local/lib/python3.9/site-packages/interactor/commander/animations.py", line 180, in action
    async with hp.TaskHolder(self.final_future, name=f"Animations::action({method})[ts]") as ts:
  File "/usr/local/lib/python3.9/site-packages/photons_app/helpers.py", line 89, in __aenter__
    return await self.start()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 182, in __aexit__
    await self.gen.__anext__()
  File "/usr/local/lib/python3.9/site-packages/photons_app/runner.py", line 70, in run
    loop.run_until_complete(waiter)
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/photons_app/runner.py", line 62, in wait
    await graceful_future
  File "/usr/local/lib/python3.9/site-packages/interactor/addon.py", line 36, in interactor
    await Server(final_future).serve(
  File "/usr/local/lib/python3.9/site-packages/whirlwind/server.py", line 28, in serve
    await self.final_future
photons_app.errors.ApplicationStopped: "The application itself was stopped"

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Something went wrong! -- ApplicationStopped
	"The application itself was stopped"
```

**Comment by delfick** [comment]
weird, I'm gonna remake the docker image with the update I made yesterday
https://github.com/delfick/photons/runs/2274983632?check_suite_focus=true

can you make it have the latest docker image when it's done and try again?

**Comment by Djelibeybi** [comment]
I deleted my comment because I was indeed testing an older build instead of the latest code. Once I used the new version, it worked as expected.

**Comment by delfick** [comment]
hahahahaha
