### ISSUE TITLE
lan:animate throws an "UnboundLocalError: local variable 'artifact' referenced before assignment" error 

### ISSUE THREAD

**Issue by Djelibeybi** [delfick/photons#51]
When I run the following command:

```bash
$ lifx lan:animate match:cap=matrix time -- '{"progress_color_range": "rainbow"}'
```
It throws this error:

```bash
23:01:41 INFO    delfick_project.option_merge.collector Adding configuration from /Users/amiller/.photons_apprc.yml
23:01:41 INFO    delfick_project.addons Found lifx.photons.interactor addon
23:01:41 INFO    delfick_project.addons Found lifx.photons.canvas addon
23:01:41 INFO    delfick_project.addons Found lifx.photons.control addon
23:01:41 INFO    delfick_project.addons Found lifx.photons.core addon
23:01:41 INFO    delfick_project.addons Found lifx.photons.pytest addon
23:01:41 INFO    delfick_project.addons Found lifx.photons.transport addon
23:01:41 INFO    delfick_project.addons Found lifx.photons.arranger addon
23:01:41 INFO    delfick_project.option_merge.collector Converting photons_app
23:01:41 INFO    delfick_project.option_merge.collector Converting target_register
23:01:41 INFO    delfick_project.option_merge.collector Converting reference_resolver_register
23:01:41 INFO    delfick_project.option_merge.collector Converting targets
23:01:41 INFO    delfick_project.option_merge.collector Converting discovery_options
23:01:41 INFO    delfick_project.option_merge.collector Converting protocol_register


Something unexpected happened!! Please file a ticket in the issue tracker! None
===============================================================================

Traceback (most recent call last):
  File "/Users/amiller/.photons/bin/lifx", line 33, in <module>
    sys.exit(load_entry_point('lifx-photons-core==0.40.1', 'console_scripts', 'lifx')())
  File "/Users/amiller/.photons/lib/python3.9/site-packages/photons_app/executor.py", line 206, in lifx_main
    return main(*args, **kwargs)
  File "/Users/amiller/.photons/lib/python3.9/site-packages/delfick_project/app.py", line 234, in main
    app.mainline(argv, **execute_args)
  File "/Users/amiller/.photons/lib/python3.9/site-packages/photons_app/executor.py", line 111, in mainline
    super(App, self).mainline(original_argv, print_errors_to, **execute_args)
  File "/Users/amiller/.photons/lib/python3.9/site-packages/delfick_project/app.py", line 312, in mainline
    self.execute(args_obj, args_dict, extra_args, handler, **execute_args)
  File "/Users/amiller/.photons/lib/python3.9/site-packages/photons_app/executor.py", line 146, in execute
    task_register.fill_task(
  File "/Users/amiller/.photons/lib/python3.9/site-packages/photons_app/tasks/tasks.py", line 102, in run_loop
    return Runner(self, kwargs).run_loop()
  File "/Users/amiller/.photons/lib/python3.9/site-packages/photons_app/tasks/runner.py", line 22, in run_loop
    self.Run(self.task.run(**self.kwargs), photons_app, target_register).run()
  File "/Users/amiller/.photons/lib/python3.9/site-packages/photons_app/tasks/runner.py", line 69, in run
    raise override from None
  File "/Users/amiller/.photons/lib/python3.9/site-packages/photons_app/tasks/runner.py", line 50, in run
    self.loop.run_until_complete(waiter)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/amiller/.photons/lib/python3.9/site-packages/photons_app/tasks/runner.py", line 85, in wait
    await task
  File "/Users/amiller/.photons/lib/python3.9/site-packages/photons_app/tasks/tasks.py", line 109, in run
    return await self.execute_task(**kwargs)
  File "/Users/amiller/.photons/lib/python3.9/site-packages/photons_canvas/addon.py", line 99, in execute_task
    layered = {"animations": [[artifact, background, options]], "animation_limit": 1}
UnboundLocalError: local variable 'artifact' referenced before assignment
```

**Comment by delfick** [comment]
oops. needs to be self.artifact

Would have broken in migration to class based tasks

**Comment by Djelibeybi** [comment]
Yep, changing it to `self.artifact` fixes the issue.
