### ISSUE TITLE
AttributeError: module 'photons_app.helpers' has no attribute 'ThreadToAsyncQueue'

### ISSUE THREAD

**Issue by gabemunro** [delfick/photons#72]
Aloha! Me again. Just updated after a while, and I keep getting stuck in a loop. Crashes on load. Seems pretty directly related to "Removed hp.ThreadToAsyncQueue" in the 0.41.0 details in the change log, but I dunno. Correlation doesn't always equal causality, right? 

Here's the log:

`2021-09-20 19:55:14,549 INFO    delfick_project.option_merge.collector Adding configuration from /Users/accountname/.photons_apprc.yml
2021-09-20 19:55:14,550 INFO    delfick_project.option_merge.collector Adding configuration from /Users/accountname/.photons-core/lifx.yml
2021-09-20 19:55:14,557 INFO    delfick_project.addons Found lifx.photons.interactor addon
2021-09-20 19:55:15,812 INFO    delfick_project.addons Found lifx.photons.canvas addon
2021-09-20 19:55:15,830 INFO    delfick_project.addons Found lifx.photons.control addon
2021-09-20 19:55:15,858 INFO    delfick_project.addons Found lifx.photons.core addon
2021-09-20 19:55:15,859 INFO    delfick_project.addons Found lifx.photons.pytest addon
2021-09-20 19:55:15,860 INFO    delfick_project.addons Found lifx.photons.transport addon
2021-09-20 19:55:15,860 INFO    delfick_project.addons Found lifx.photons.arranger addon
2021-09-20 19:55:15,897 INFO    delfick_project.option_merge.collector Converting photons_app
2021-09-20 19:55:15,899 INFO    delfick_project.option_merge.collector Converting target_register
2021-09-20 19:55:15,900 INFO    delfick_project.option_merge.collector Converting reference_resolver_register
2021-09-20 19:55:15,900 INFO    delfick_project.option_merge.collector Converting targets
2021-09-20 19:55:15,903 INFO    delfick_project.option_merge.collector Converting discovery_options
2021-09-20 19:55:15,905 INFO    delfick_project.option_merge.collector Converting protocol_register
2021-09-20 19:55:16,415 INFO    delfick_project.option_merge.collector Converting interactor
2021-09-20 19:55:16,722 INFO    alembic.runtime.migration Context impl SQLiteImpl.
2021-09-20 19:55:16,722 INFO    alembic.runtime.migration Will assume non-transactional DDL.

Something unexpected happened!! Please file a ticket in the issue tracker! None
===============================================================================

Traceback (most recent call last):
  File "/Users/accountname/.photons-core/bin/lifx", line 11, in <module>
    load_entry_point('lifx-photons-core==0.41.0', 'console_scripts', 'lifx')()
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_app/executor.py", line 206, in lifx_main
    return main(*args, **kwargs)
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/delfick_project/app.py", line 234, in main
    app.mainline(argv, **execute_args)
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_app/executor.py", line 111, in mainline
    super(App, self).mainline(original_argv, print_errors_to, **execute_args)
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/delfick_project/app.py", line 312, in mainline
    self.execute(args_obj, args_dict, extra_args, handler, **execute_args)
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_app/executor.py", line 146, in execute
    task_register.fill_task(
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_app/tasks/tasks.py", line 148, in run_loop
    super().run_loop(**kwargs)
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_app/tasks/tasks.py", line 102, in run_loop
    return Runner(self, kwargs).run_loop()
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_app/tasks/runner.py", line 22, in run_loop
    self.Run(self.task.run(**self.kwargs), photons_app, target_register).run()
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_app/tasks/runner.py", line 69, in run
    raise override from None
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_app/tasks/runner.py", line 50, in run
    self.loop.run_until_complete(waiter)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_app/tasks/runner.py", line 85, in wait
    await task
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/photons_app/tasks/tasks.py", line 109, in run
    return await self.execute_task(**kwargs)
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/interactor/addon.py", line 38, in execute_task
    await Server(
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/whirlwind/server.py", line 22, in serve
    self.server_kwargs = await self.setup(*args, **kwargs)
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/interactor/server.py", line 55, in setup
    self.db_queue = __import__("interactor.database.db_queue").database.db_queue.DBQueue(
  File "/Users/accountname/.photons-core/lib/python3.8/site-packages/interactor/database/db_queue.py", line 34, in <module>
    class DBQueue(hp.ThreadToAsyncQueue):
AttributeError: module 'photons_app.helpers' has no attribute 'ThreadToAsyncQueue'`

**Comment by delfick** [comment]
looks like you have a new version of photons but not a new version of interactor.

**Comment by gabemunro** [comment]
Derp. Thank you. That was it. Greatly appreciate the quick response.

**Comment by delfick** [comment]
:D
